# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('handicap', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
        migrations.AddField(
            model_name='golfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagueTracker.User'),
        ),
    ]
