# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70, null=True, unique=True),
        ),
    ]
