# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueTracker', '0004_auto_20160628_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='display_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
