# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueTracker', '0005_auto_20160628_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('members', models.ManyToManyField(to='leagueTracker.Golfer')),
            ],
        ),
    ]
